# 'sudo required' will give os 7,5 GB memory, but has slower startup times, as we start a VM instead of a Container
sudo: required
language: python
cache: pip

python: 2.7

# This is a big repository so break Travis CI work into 3 test jobs.
env:
  - CHUNK=0
  - CHUNK=1
  - CHUNK=2

jobs:
  include:
    - stage: lint
      before_install: skip
      install:
        - pip install flake8 flake8-import-order planemo
        - planemo --version
        - echo $TRAVIS_COMMIT_RANGE
        - |
          planemo ci_find_repos --exclude_from .tt_blacklist \
                                --changed_in_commit_range "$TRAVIS_COMMIT_RANGE" \
                                --output changed_repositories.list
        - cat changed_repositories.list
      script:
        - set -e
        - cd "$TRAVIS_BUILD_DIR" && flake8 --exclude=.git .
        - while read -r DIR; do planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error --recursive "$DIR"; done < changed_repositories.list

    - stage: test

    - stage: deploy
      before_install: skip
      install:
        - pip install planemo
        - planemo --version
        - echo $TRAVIS_COMMIT_RANGE
        - |
          planemo ci_find_repos --exclude_from .tt_blacklist \
                                --changed_in_commit_range "$TRAVIS_COMMIT_RANGE" \
                                --output changed_repositories.list
        - cat changed_repositories.list
      script:
        - set -e
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then
            while read -r DIR; do planemo shed_update --shed_target testtoolshed --shed_email "$SHED_EMAIL" --shed_password "$SHED_PASSWORD" --force_repository_creation "$DIR" || exit 1; done < changed_repositories.list
            while read -r DIR; do planemo shed_update --shed_target toolshed --shed_email "$SHED_EMAIL" --shed_password "$SHED_PASSWORD" --force_repository_creation "$DIR" || exit 1; done < changed_repositories.list
          fi

before_install:
  - export GALAXY_REPO=https://github.com/galaxyproject/galaxy
  - export GALAXY_RELEASE=release_17.05
  - export PLANEMO_CONDA_PREFIX="$HOME/conda"
  - unset JAVA_HOME

install:
  - pip install planemo
  - planemo conda_init
  - export PATH="$PLANEMO_CONDA_PREFIX/bin:$PATH"
  - planemo --version
  - conda --version
  - git diff --quiet "$TRAVIS_COMMIT_RANGE" -- ; GIT_DIFF_EXIT_CODE=$?
  - |
    if [ "$GIT_DIFF_EXIT_CODE" -gt 1 ] ; then
      git remote set-branches --add origin master;
      git fetch;
      TRAVIS_COMMIT_RANGE=origin/master...;
    fi
  - echo $TRAVIS_COMMIT_RANGE
  - |
      planemo ci_find_repos --exclude_from .tt_blacklist \
                            --changed_in_commit_range "$TRAVIS_COMMIT_RANGE" \
                            --output changed_repositories.list
  - |
    if [ -s changed_repositories.list ]; then
        planemo ci_find_tools --exclude data_managers \
                              --exclude packages \
                              --chunk_count 3 --chunk "${CHUNK}" \
                              --output changed_tools_chunk.list \
                              $(cat changed_repositories.list)
        cat changed_tools_chunk.list
    fi
  - cat changed_repositories.list

script:
  - set -e
  - |
    if [ -s changed_tools_chunk.list ]; then
        planemo test --conda_dependency_resolution --conda_auto_install --galaxy_branch "$GALAXY_RELEASE" --galaxy_source "$GALAXY_REPO" $(cat changed_tools_chunk.list)
    fi
