categories:
- Data Managers
description: Data Manager for mothur reference data
long_description:
name: data_manager_mothur_toolsuite
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/data_managers/data_manager_mothur_toolsuite
type: unrestricted
